### PR TITLE
M1 chipset compatibility

### PR DESCRIPTION
**Pull request by lleites**
Changes done to support Mac M1 chipsets and other small fixes

- Updated pyarrow to version 8, previous version does not work with M1
- Added new exception to pylint because of update, I can either ignore this or update the code for this check.
- Updated batect to the latest version (0.79.1) previous version had a problem with jenv
- Added specific platform to python image for M1 chipset compatibility
- Added option for poetry to not check for local virtual envs like .venv, this does not wok well with batect.

- [ ] Check if this does not break other chipsets/platforms

### CODE REVIEW

**Comment by sendy511** [comment]
I use the .\batect unit-test to verify the upgrade looks fine on window 10 env.

@lleites  the change looks good, let me know if there are more test needed.

**Comment by lleites** [comment]
Thanks for testing this @sendy511, can you please run `./go.sh run-docker-desktop-unit-test`?
This case builds and uses the docker image, I did some changes there too.

**Comment by lleites** [comment]
> go.sh ? typo? .\go.ps1 works.. @lleites

Yes, sorry, that is the Unix version, I think we do not need more tests from your side. Thank you very much!

**Review by svishal9 — APPROVED** [review]
LGTM

**Pull request merged**
